package app.vaultline;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.text.InputType;
import android.view.*;
import android.view.inputmethod.EditorInfo;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.*;

public final class MainActivity extends Activity {
 static final int BG=0xff171719,PANEL=0xff222224,GOLD=0xffdbb55c,TEXT=0xffe2e2e2,MUTED=0xffaaaaaa;
 static final int EXPORT=10,IMPORT=11,BACKUP=12,RESTORE=13;
 final Handler handler=new Handler(Looper.getMainLooper());final ExecutorService worker=Executors.newSingleThreadExecutor();
 VaultCore.Vault vault;byte[] key,salt;File vaultFile;String folder="",selectedPath="";Object selectedValue;
 LinearLayout page,content;EditText search;TextView status,details;Button reveal;boolean visible,busy,picking;long lastActive=0,showUntil=0;int epoch=0;Dialog modal,progress;
 static final class Session {VaultCore.Vault vault;byte[] key,salt;Session(VaultCore.Vault v,byte[] k,byte[] s){vault=v;key=k;salt=s;}void clear(){Arrays.fill(key,(byte)0);}}
 interface Work {Object run() throws Exception;}interface Done {void run(Object value)throws Exception;}interface Change {void run(VaultCore.Vault v)throws Exception;}
 int dp(float n){return (int)(getResources().getDisplayMetrics().density*n+0.5f);}
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().addFlags(WindowManager.LayoutParams.FLAG_SECURE);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);vaultFile=new File(getFilesDir(),"vault.jx");showUnlock();handler.postDelayed(clock,1000);}
 final Runnable clock=new Runnable(){public void run(){if(vault!=null){if(SystemClock.elapsedRealtime()-lastActive>=300000)lock();else if(visible&&SystemClock.elapsedRealtime()>=showUntil){visible=false;renderDetails();}}handler.postDelayed(this,1000);}};
 @Override public void onUserInteraction(){super.onUserInteraction();lastActive=SystemClock.elapsedRealtime();}
 @Override protected void onStop(){super.onStop();if(!picking)lock();}
 @Override protected void onResume(){super.onResume();if(vault!=null&&SystemClock.elapsedRealtime()-lastActive>=300000)lock();}
 @Override protected void onDestroy(){epoch++;if(key!=null)Arrays.fill(key,(byte)0);handler.removeCallbacksAndMessages(null);worker.shutdown();super.onDestroy();}
 @Override public void onBackPressed(){if(vault==null){super.onBackPressed();return;}if(!selectedPath.isEmpty()){showHome();return;}if(!folder.isEmpty()){folder=VaultCore.parent(folder);showHome();return;}lock();}
 GradientDrawable background(int fill,int stroke){GradientDrawable d=new GradientDrawable();d.setColor(fill);d.setCornerRadius(dp(10));if(stroke!=0)d.setStroke(dp(1),stroke);return d;}
 LinearLayout column(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}
 TextView text(String s,int size,int color){TextView t=new TextView(this);t.setText(s);t.setTextColor(color);t.setTextSize(size);t.setPadding(0,dp(6),0,dp(6));return t;}
 Button button(String s,Runnable action){Button b=new Button(this);b.setText(s);b.setTextColor(GOLD);b.setTextSize(14);b.setAllCaps(false);b.setMinHeight(dp(48));b.setMinimumHeight(dp(48));b.setBackground(background(PANEL,0xff514938));b.setPadding(dp(12),0,dp(12),0);b.setOnClickListener(v->{lastActive=SystemClock.elapsedRealtime();if(!busy)action.run();});return b;}
 EditText input(String hint,boolean secret,boolean multiline){EditText t=new EditText(this);t.setTextColor(TEXT);t.setHintTextColor(MUTED);t.setTextSize(15);t.setHint(hint);t.setPadding(dp(12),dp(10),dp(12),dp(10));t.setBackground(background(PANEL,0xff514938));t.setInputType(secret?InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD:InputType.TYPE_CLASS_TEXT|(multiline?InputType.TYPE_TEXT_FLAG_MULTI_LINE:InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS));t.setSingleLine(!multiline);t.setImportantForAutofill(View.IMPORTANT_FOR_AUTOFILL_NO_EXCLUDE_DESCENDANTS);t.setSaveEnabled(false);return t;}
 void gap(LinearLayout l,int h){View v=new View(this);l.addView(v,new LinearLayout.LayoutParams(1,dp(h)));}
 void addButton(LinearLayout row,Button b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,dp(48));p.setMargins(0,0,dp(8),0);row.addView(b,p);}
 LinearLayout actions(LinearLayout owner){HorizontalScrollView sc=new HorizontalScrollView(this);sc.setHorizontalScrollBarEnabled(false);LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);sc.addView(row);owner.addView(sc);return row;}
 void base(String title,String subtitle){page=column();page.setBackgroundColor(BG);page.setPadding(dp(18),dp(12),dp(18),dp(10));setContentView(page);TextView name=text(title,28,GOLD);name.setTypeface(Typeface.DEFAULT,Typeface.BOLD);page.addView(name);if(subtitle!=null)page.addView(text(subtitle,12,MUTED));}
 void message(String s){if(status!=null)status.setText(s);Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
 void error(Exception e){new AlertDialog.Builder(this).setTitle("Vaultline").setMessage(e.getMessage()==null?"操作未完成":e.getMessage()).setPositiveButton("确定",null).show();}
 void task(String label,Work work,Done done){if(busy)return;busy=true;final int token=epoch;ProgressDialog p=new ProgressDialog(this);p.setMessage(label);p.setCancelable(false);progress=p;p.show();worker.execute(()->{Object value=null;Exception failure=null;try{value=work.run();}catch(Exception e){failure=e;}final Object result=value;final Exception issue=failure;handler.post(()->{if(p.isShowing())p.dismiss();busy=false;if(token!=epoch||isFinishing()||isDestroyed()){if(result instanceof Session)((Session)result).clear();return;}try{if(issue!=null)throw issue;done.run(result);}catch(Exception e){error(e);}});});}
 void showUnlock(){selectedValue=null;details=null;status=null;search=null;selectedPath="";base("Vaultline","本地隐私保险库  ·  离线加密");ScrollView scroll=new ScrollView(this);LinearLayout body=column();scroll.setFillViewport(true);scroll.addView(body);page.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));gap(body,28);boolean create=!vaultFile.exists();body.addView(text(create?"创建你的保险库":"欢迎回来",22,TEXT));body.addView(text(create?"设置至少 12 个字符的主密码。请妥善保存，遗失后无法恢复。":"输入主密码，解锁本机保存的账号信息。",14,MUTED));gap(body,20);EditText password=input("主密码",true,false);body.addView(password);gap(body,12);EditText confirm=input("再次输入主密码",true,false);if(create){body.addView(confirm);gap(body,12);}Button unlock=button(create?"创建保险库":"解锁",()->{String s=password.getText().toString();if(create&&(s.length()<12||!s.equals(confirm.getText().toString()))){message("密码至少 12 个字符，且两次输入需一致");return;}char[] pass=s.toCharArray();password.setText("");confirm.setText("");task("正在解锁…",()->{byte[] k=null;try{if(vaultFile.exists()){byte[] blob=VaultCore.read(new FileInputStream(vaultFile)),salt=VaultCore.salt(blob);k=VaultCore.derive(pass,salt);byte[] plain=VaultCore.open(blob,k);try{return new Session(VaultCore.deserialize(plain),k,salt);}finally{Arrays.fill(plain,(byte)0);}}byte[] salt=VaultCore.random(16);k=VaultCore.derive(pass,salt);VaultCore.Vault v=new VaultCore.Vault();save(v,k,salt);return new Session(v,k,salt);}catch(Exception ex){if(k!=null)Arrays.fill(k,(byte)0);throw ex;}finally{Arrays.fill(pass,'\0');}},value->{Session session=(Session)value;vault=session.vault;key=session.key;salt=session.salt;lastActive=SystemClock.elapsedRealtime();showHome();});});body.addView(unlock);gap(body,18);body.addView(text("数据保存在应用私有目录。卸载应用会删除本机数据，请先导出或备份。",12,MUTED));}
 void save(VaultCore.Vault v,byte[] k,byte[] s)throws Exception{byte[] plain=VaultCore.serialize(v);try{if(plain.length>VaultCore.LIMIT)throw new Exception("保险库过大");VaultCore.atomic(vaultFile,VaultCore.seal(plain,k,s));}finally{Arrays.fill(plain,(byte)0);}}
 void lock(){epoch++;if(modal!=null){modal.dismiss();modal=null;}if(progress!=null)progress.dismiss();if(key!=null)Arrays.fill(key,(byte)0);key=null;vault=null;selectedValue=null;visible=false;if(!isFinishing()&&!isDestroyed())showUnlock();}
 void change(Change action,String success){if(vault==null)return;try{VaultCore.Vault next=vault.copy();action.run(next);VaultCore.validate(next);byte[] k=key.clone(),s=salt.clone();task("正在保存…",()->{try{save(next,k,s);return next;}finally{Arrays.fill(k,(byte)0);}},result->{vault=(VaultCore.Vault)result;if(!folder.isEmpty()&&VaultCore.folder(vault,folder)==null)folder="";showHome();message(success);});}catch(Exception e){error(e);}}
 void showHome(){if(vault==null)return;selectedPath="";selectedValue=null;visible=false;details=null;base("Vaultline","离线存储  /  已加密");LinearLayout row=actions(page);addButton(row,button("＋ 分组",this::newFolder));addButton(row,button("＋ 账号",()->editEntry(null)));addButton(row,button("导出数据",()->pick(EXPORT)));addButton(row,button("一键导入",()->pick(IMPORT)));addButton(row,button("更多",this::more));gap(page,12);LinearLayout find=new LinearLayout(this);find.setGravity(Gravity.CENTER_VERTICAL);search=input("目录 / 标签 / 字段",false,false);find.addView(search,new LinearLayout.LayoutParams(0,dp(50),1));Button go=button("查找",this::search);LinearLayout.LayoutParams goParams=new LinearLayout.LayoutParams(dp(70),dp(50));goParams.leftMargin=dp(8);find.addView(go,goParams);page.addView(find);search.setImeOptions(EditorInfo.IME_ACTION_SEARCH);search.setOnEditorActionListener((v,id,event)->{if(id==EditorInfo.IME_ACTION_SEARCH){search();return true;}return false;});gap(page,8);LinearLayout nav=actions(page);addButton(nav,button("保险库",()->{folder="";showHome();}));if(!folder.isEmpty())addButton(nav,button("返回上级",()->{folder=VaultCore.parent(folder);showHome();}));TextView crumb=text(folder.isEmpty()?"全部分组":folder,14,GOLD);page.addView(crumb);ScrollView scroll=new ScrollView(this);content=column();scroll.addView(content);page.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));status=text(vault.entries.size()+" 个账号 · 长按项目可编辑",12,MUTED);page.addView(status);List<String> dirs=new ArrayList<>(vault.folders);Collections.sort(dirs,String.CASE_INSENSITIVE_ORDER);for(String f:dirs)if(VaultCore.eq(VaultCore.parent(f),folder))folderRow(f);List<VaultCore.Entry> es=new ArrayList<>(vault.entries);Collections.sort(es,(a,b)->a.path.compareToIgnoreCase(b.path));for(VaultCore.Entry e:es)if(VaultCore.eq(VaultCore.parent(e.path),folder))entryRow(e);if(content.getChildCount()==0)content.addView(text("这里还没有内容\n创建分组或账号，或导入已有数据。",15,MUTED));}
 void folderRow(String f){TextView t=text("▸  "+VaultCore.name(f),17,TEXT);t.setPadding(dp(14),dp(18),dp(14),dp(18));t.setBackground(background(PANEL,0));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(8);content.addView(t,p);t.setOnClickListener(v->{folder=f;showHome();});t.setOnLongClickListener(v->{folderMenu(f);return true;});}
 void entryRow(VaultCore.Entry e){TextView t=text(VaultCore.name(e.path)+"\n"+e.level+"  ·  "+VaultCore.parent(e.path),16,TEXT);t.setPadding(dp(14),dp(14),dp(14),dp(14));t.setBackground(background(PANEL,0));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(8);content.addView(t,p);t.setOnClickListener(v->showEntry(e,e.fields));t.setOnLongClickListener(v->{entryMenu(e);return true;});}
 void search(){if(vault==null||search==null)return;String q=VaultCore.normalize(search.getText().toString());if(q.isEmpty()){showHome();return;}String f=VaultCore.folder(vault,q);if(f!=null){folder=f;showHome();return;}VaultCore.Entry found=null;for(VaultCore.Entry e:vault.entries)if(VaultCore.eq(e.path,q)||q.toLowerCase(Locale.ROOT).startsWith(e.path.toLowerCase(Locale.ROOT)+"/"))if(found==null||e.path.length()>found.path.length())found=e;try{if(found!=null){showEntry(found,VaultCore.resolve(found,q));return;}content.removeAllViews();for(VaultCore.Entry e:vault.entries)if(e.path.toLowerCase(Locale.ROOT).contains(q.toLowerCase(Locale.ROOT)))entryRow(e);status.setText("找到 "+content.getChildCount()+" 个账号");}catch(Exception e){error(e);}}
 void showEntry(VaultCore.Entry e,Object value){if(vault==null)return;selectedPath=e.path;selectedValue=value;visible=false;base(VaultCore.name(e.path),e.path+"\n"+e.level+"  ·  "+(e.updated==null?"":e.updated));LinearLayout row=actions(page);addButton(row,button("返回",this::showHome));addButton(row,button("编辑",()->editEntry(e)));addButton(row,button("删除",()->deleteEntry(e)));gap(page,14);ScrollView scroll=new ScrollView(this);details=text("",16,TEXT);details.setPadding(dp(16),dp(16),dp(16),dp(16));details.setBackground(background(PANEL,0));details.setTextIsSelectable(true);details.setSaveEnabled(false);scroll.addView(details);page.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));gap(page,14);LinearLayout actions=actions(page);reveal=button("显示 30 秒",()->{visible=!visible;showUntil=SystemClock.elapsedRealtime()+30000;renderDetails();});addButton(actions,reveal);addButton(actions,button("复制内容",this::copy));status=text("应用不定时清空剪贴板",12,MUTED);page.addView(status);renderDetails();}
 void renderDetails(){if(details==null||selectedValue==null)return;try{if(visible)details.setText(VaultCore.displayLines(selectedValue));else if(selectedValue instanceof JSONObject){List<String> rows=new ArrayList<>();Iterator<String> keys=((JSONObject)selectedValue).keys();while(keys.hasNext())rows.add(keys.next()+"：••••••••");details.setText(String.join("\n\n",rows));}else details.setText("••••••••");if(reveal!=null)reveal.setText(visible?"隐藏内容":"显示 30 秒");}catch(Exception e){error(e);}}
 void copy(){if(vault==null)return;try{String value=VaultCore.copyLines(selectedValue);if(value.isEmpty()){message("当前内容为空");return;}ClipData clip=ClipData.newPlainText("Vaultline",value);PersistableBundle extras=new PersistableBundle();extras.putBoolean("android.content.extra.IS_SENSITIVE",true);clip.getDescription().setExtras(extras);((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(clip);message("已复制内容");}catch(Exception e){error(e);}}
 interface StringAction{void run(String s)throws Exception;}
 void ask(String title,String hint,String value,boolean secret,StringAction action){EditText edit=input(hint,secret,false);edit.setText(value);LinearLayout box=column();box.setPadding(dp(20),dp(12),dp(20),dp(6));box.addView(edit);AlertDialog d=new AlertDialog.Builder(this).setTitle(title).setView(box).setPositiveButton("确定",null).setNegativeButton("取消",null).create();modal=d;d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{if(busy)return;try{String result=edit.getText().toString();action.run(result);edit.setText("");d.dismiss();}catch(Exception e){error(e);}}));d.show();}
 void newFolder(){ask("新建分组","完整路径",folder.isEmpty()?"":folder+"/",false,p->{String dest=VaultCore.normalize(p);VaultCore.path(dest);change(v->VaultCore.addFolder(v,dest),"已创建分组");});}
 void editEntry(VaultCore.Entry e){try{LinearLayout body=column();body.setPadding(dp(18),dp(6),dp(18),dp(8));body.addView(text("完整路径 / 最后一段为标签",13,MUTED));EditText path=input("account/wechat/work-account",false,false);path.setText(e==null?(folder.isEmpty()?"":folder+"/")+"work-account":e.path);body.addView(path);gap(body,10);body.addView(text("隐私级别",13,MUTED));Spinner level=new Spinner(this);ArrayAdapter<String> adapter=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"普通","敏感","机密"});level.setAdapter(adapter);level.setSelection(e==null?1:Arrays.asList("普通","敏感","机密").indexOf(e.level));body.addView(level);body.addView(text("账号 JSON · 编辑时显示明文",13,MUTED));EditText json=input("JSON 对象",false,true);json.setGravity(Gravity.TOP);json.setTypeface(Typeface.MONOSPACE);json.setMinLines(7);json.setText(e==null?"{\n  \"address\": \"\",\n  \"password\": \"\"\n}":e.fields.toString(2));body.addView(json);ScrollView scroll=new ScrollView(this);scroll.addView(body);AlertDialog dialog=new AlertDialog.Builder(this).setTitle(e==null?"新建账号":"编辑账号").setView(scroll).setPositiveButton("保存",null).setNegativeButton("取消",null).create();modal=dialog;dialog.setOnShowListener(x->{dialog.getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);dialog.getButton(-1).setOnClickListener(v->{if(busy)return;try{String p=VaultCore.normalize(path.getText().toString());VaultCore.path(p);JSONObject fields=new JSONObject(json.getText().toString());VaultCore.Entry next=new VaultCore.Entry(p,level.getSelectedItem().toString(),fields,VaultCore.now());change(current->VaultCore.put(current,next,e==null?null:e.path),"已保存账号");dialog.dismiss();}catch(Exception ex){error(ex);}});});dialog.show();}catch(Exception ex){error(ex);}}
 void entryMenu(VaultCore.Entry e){modal=new AlertDialog.Builder(this).setTitle(VaultCore.name(e.path)).setItems(new String[]{"编辑 / 移动","删除"},(d,n)->{if(n==0)editEntry(e);else deleteEntry(e);}).show();}
 void deleteEntry(VaultCore.Entry e){modal=new AlertDialog.Builder(this).setTitle("删除账号？").setMessage(e.path).setNegativeButton("取消",null).setPositiveButton("删除",(d,n)->change(v->v.entries.remove(VaultCore.entry(v,e.path)),"已删除账号")).show();}
 void folderMenu(String f){modal=new AlertDialog.Builder(this).setTitle(f).setItems(new String[]{"编辑 / 移动","删除分组"},(d,n)->{if(n==0)ask("编辑分组","新的完整路径",f,false,p->{String dest=VaultCore.normalize(p);VaultCore.path(dest);change(v->VaultCore.moveFolder(v,f,dest),"已更新分组");});else{int count=0;for(VaultCore.Entry e:vault.entries)if(VaultCore.under(e.path,f))count++;modal=new AlertDialog.Builder(this).setTitle("删除分组？").setMessage("将删除 "+f+" 及其子分组和 "+count+" 个账号").setNegativeButton("取消",null).setPositiveButton("删除",(a,b)->change(v->{v.entries.removeIf(e->VaultCore.under(e.path,f));v.folders.removeIf(x->VaultCore.under(x,f));},"已删除分组")).show();}}).show();}
 void more(){modal=new AlertDialog.Builder(this).setTitle("Vaultline").setItems(new String[]{"加密备份","恢复备份","修改主密码","锁定","帮助"},(d,n)->{if(n==0)pick(BACKUP);else if(n==1)pick(RESTORE);else if(n==2)password();else if(n==3)lock();else help();}).show();}
 void help(){modal=new AlertDialog.Builder(this).setTitle("使用说明").setMessage("目录可以逐层打开，长按分组或账号可编辑、移动和删除。\n\n搜索路径示例：\naccount/wechat/work-account/password\n字段名中的 / 写成 ~1，~ 写成 ~0。\n\n复制账号时按行复制字段值；定位单一字段可直接复制。\n\n导出数据会保存全部账号为 JSON，一键导入可读取其他设备的导出文件；重复账号跳过，冲突账号改名保留。\n\n加密备份可使用 .jx 文件，主密码修改后历史备份仍使用原密码。\n\n切到后台时锁定，使用系统文件选择器期间暂缓；闲置 5 分钟也会锁定。应用不定时清空剪贴板，但系统可能自动处理剪贴板。\n\n卸载应用会删除本机数据，请先导出或备份。\n版本 1.0.0").setPositiveButton("知道了",null).show();}
 void password(){ask("修改主密码","新密码（至少 12 个字符）","",true,p->{if(p.length()<12)throw new Exception("密码至少 12 个字符");handler.post(()->ask("确认主密码","再次输入新密码","",true,c->{if(!p.equals(c))throw new Exception("两次密码不一致");char[] pass=p.toCharArray();VaultCore.Vault snapshot=vault.copy();task("正在更新密码…",()->{byte[] s=VaultCore.random(16),k=null;try{k=VaultCore.derive(pass,s);save(snapshot,k,s);return new Session(snapshot,k,s);}catch(Exception e){if(k!=null)Arrays.fill(k,(byte)0);throw e;}finally{Arrays.fill(pass,'\0');}},value->{Session session=(Session)value;Arrays.fill(key,(byte)0);key=session.key;salt=session.salt;message("主密码已更新");});}));});}
 void pick(int operation){if(vault==null||busy)return;Intent intent;if(operation==EXPORT||operation==BACKUP){intent=new Intent(Intent.ACTION_CREATE_DOCUMENT);intent.addCategory(Intent.CATEGORY_OPENABLE);intent.setType(operation==EXPORT?"application/json":"application/octet-stream");intent.putExtra(Intent.EXTRA_TITLE,"Vaultline-"+System.currentTimeMillis()+(operation==EXPORT?".json":".jx"));}else{intent=new Intent(Intent.ACTION_OPEN_DOCUMENT);intent.addCategory(Intent.CATEGORY_OPENABLE);intent.setType("*/*");}picking=true;try{startActivityForResult(intent,operation);}catch(Exception e){picking=false;error(e);}}
 @Override protected void onActivityResult(int request,int result,Intent intent){super.onActivityResult(request,result,intent);picking=false;if(result!=RESULT_OK||intent==null||intent.getData()==null)return;if(vault==null){message("请解锁后重新选择文件");return;}Uri uri=intent.getData();try{if(request==EXPORT){byte[] bytes=VaultCore.export(vault).toString(2).getBytes(StandardCharsets.UTF_8);int count=vault.entries.size();task("正在导出…",()->{try(OutputStream out=getContentResolver().openOutputStream(uri,"wt")){if(out==null)throw new Exception("无法打开保存位置");out.write(bytes);return null;}finally{Arrays.fill(bytes,(byte)0);}},v->message("已导出 "+count+" 个账号"));}else if(request==BACKUP){task("正在备份…",()->{byte[] bytes=VaultCore.read(new FileInputStream(vaultFile));try(OutputStream out=getContentResolver().openOutputStream(uri,"wt")){if(out==null)throw new Exception("无法打开保存位置");out.write(bytes);}return null;},v->message("已保存加密备份"));}else if(request==IMPORT){VaultCore.Vault snapshot=vault.copy();byte[] k=key.clone(),s=salt.clone();task("正在导入…",()->{byte[] data=null;try{data=VaultCore.read(getContentResolver().openInputStream(uri));VaultCore.Merge merged=VaultCore.merge(snapshot,VaultCore.parseExport(new String(data,StandardCharsets.UTF_8)));save(merged.vault,k,s);return merged;}finally{Arrays.fill(k,(byte)0);if(data!=null)Arrays.fill(data,(byte)0);}},v->{VaultCore.Merge merged=(VaultCore.Merge)v;vault=merged.vault;showHome();message("已导入 "+merged.added+" 个账号，跳过 "+merged.skipped+" 个重复账号，重命名 "+merged.renamed+" 个冲突账号");});}else if(request==RESTORE)restore(uri);}catch(Exception e){error(e);}}
 void restore(Uri uri){ask("恢复加密备份","输入该备份的主密码","",true,p->{char[] pass=p.toCharArray();task("正在验证备份…",()->{byte[] bytes=null,k=null,plain=null;try{bytes=VaultCore.read(getContentResolver().openInputStream(uri));k=VaultCore.derive(pass,VaultCore.salt(bytes));plain=VaultCore.open(bytes,k);return VaultCore.deserialize(plain);}finally{Arrays.fill(pass,'\0');if(k!=null)Arrays.fill(k,(byte)0);if(plain!=null)Arrays.fill(plain,(byte)0);}},v->{VaultCore.Vault restored=(VaultCore.Vault)v;modal=new AlertDialog.Builder(this).setTitle("恢复备份？").setMessage("将替换当前保险库为备份中的 "+restored.entries.size()+" 个账号。恢复前保留加密副本。").setNegativeButton("取消",null).setPositiveButton("恢复",(a,b)->{byte[] k=key.clone(),s=salt.clone();task("正在恢复…",()->{try{File backup=new File(getFilesDir(),"vault-before-restore-"+System.currentTimeMillis()+".jx");java.nio.file.Files.copy(vaultFile.toPath(),backup.toPath());save(restored,k,s);return restored;}finally{Arrays.fill(k,(byte)0);}},data->{vault=(VaultCore.Vault)data;folder="";showHome();message("已恢复备份");});}).show();});});}
}
