package app.vaultline;

import org.json.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.security.*;
import java.util.*;
import javax.crypto.*;
import javax.crypto.spec.*;

public final class VaultCore {
 public static final int LIMIT=32000000;
 public static final class Entry {
  public String path,level,updated;public JSONObject fields;
  public Entry(String p,String l,JSONObject f,String u){path=p;level=l;fields=f;updated=u;}
  public Entry copy() throws Exception{return new Entry(path,level,new JSONObject(fields.toString()),updated);}
 }
 public static final class Vault {
  public final List<String> folders=new ArrayList<>();public final List<Entry> entries=new ArrayList<>();
  public Vault copy() throws Exception{Vault v=new Vault();v.folders.addAll(folders);for(Entry e:entries)v.entries.add(e.copy());return v;}
 }
 public static final class Merge {public Vault vault;public int added,skipped,renamed;}
 public static String normalize(String p){p=p.trim();while(p.startsWith("/"))p=p.substring(1);while(p.endsWith("/"))p=p.substring(0,p.length()-1);return p;}
 public static boolean eq(String a,String b){return a.equalsIgnoreCase(b);}
 public static boolean under(String p,String f){return f.isEmpty()||eq(p,f)||p.regionMatches(true,0,f+"/",0,f.length()+1);}
 public static String parent(String p){int i=p.lastIndexOf('/');return i<0?"":p.substring(0,i);}
 public static String name(String p){return p.substring(p.lastIndexOf('/')+1);}
 public static String now(){return java.time.Instant.now().toString();}
 public static void path(String p)throws Exception{if(p==null||p.length()==0||p.length()>500||!p.equals(normalize(p)))throw new Exception("路径不能为空，且最多 500 个字符");for(String bit:p.split("/",-1)){if(bit.isEmpty()||!bit.equals(bit.trim())||bit.equals(".")||bit.equals(".."))throw new Exception("目录路径无效");for(char c:bit.toCharArray())if(c<32||c=='\\')throw new Exception("路径不能包含控制字符或反斜线");}}
 public static Entry entry(Vault v,String p){for(Entry e:v.entries)if(eq(e.path,p))return e;return null;}
 public static String folder(Vault v,String p){for(String f:v.folders)if(eq(f,p))return f;return null;}
 public static void addFolder(Vault v,String p)throws Exception{path(p);String t="";for(String bit:p.split("/")){t=t.isEmpty()?bit:t+"/"+bit;if(entry(v,t)!=null)throw new Exception("该路径已被账号占用");if(folder(v,t)==null)v.folders.add(t);}}
 public static void put(Vault v,Entry e,String old)throws Exception{path(e.path);Entry existing=entry(v,e.path);if((existing!=null&&(old==null||!eq(existing.path,old)))||folder(v,e.path)!=null)throw new Exception("路径已存在，请换一个标签");if(!parent(e.path).isEmpty())addFolder(v,parent(e.path));if(old!=null){Entry original=entry(v,old);v.entries.remove(original);}v.entries.add(e);}
 public static void validate(Vault v)throws Exception{Set<String> used=new HashSet<>();for(String f:v.folders){path(f);if(!used.add(f.toLowerCase(Locale.ROOT)))throw new Exception("重复分组");}for(Entry e:v.entries){path(e.path);if(e.fields==null||!Arrays.asList("普通","敏感","机密").contains(e.level)||!used.add(e.path.toLowerCase(Locale.ROOT)))throw new Exception("重复或无效的账号");}for(String p:used)if(!parent(p).isEmpty()&&folder(v,parent(p))==null)throw new Exception("缺少父目录");}
 public static Object resolve(Entry e,String q)throws Exception{Object value=e.fields;if(eq(e.path,q))return value;for(String bit:q.substring(e.path.length()+1).split("/",-1)){String key=bit.replace("~1","/").replace("~0","~");if(value instanceof JSONObject){JSONObject o=(JSONObject)value;if(!o.has(key))throw new Exception("字段不存在："+key);value=o.get(key);}else if(value instanceof JSONArray){try{value=((JSONArray)value).get(Integer.parseInt(key));}catch(Exception ex){throw new Exception("数组下标不存在："+key);}}else throw new Exception("字段不存在："+key);}return value;}
 public static String copyLines(Object o)throws Exception{List<String> lines=new ArrayList<>();flatten(o,"",false,lines);return String.join("\n",lines);}
 public static String displayLines(Object o)throws Exception{List<String> lines=new ArrayList<>();flatten(o,"",true,lines);return String.join("\n\n",lines);}
 static void flatten(Object o,String p,boolean labels,List<String> lines)throws Exception{if(o instanceof JSONObject){JSONObject d=(JSONObject)o;Iterator<String> keys=d.keys();while(keys.hasNext()){String k=keys.next();flatten(d.get(k),p.isEmpty()?k:p+" / "+k,labels,lines);}}else if(o instanceof JSONArray){JSONArray a=(JSONArray)o;for(int i=0;i<a.length();i++)flatten(a.get(i),p+"["+i+"]",labels,lines);}else lines.add((labels&&!p.isEmpty()?p+"：":"")+(o==null||o==JSONObject.NULL?"":String.valueOf(o)));}
 public static String canonical(Object o)throws Exception{if(o instanceof JSONObject){JSONObject d=(JSONObject)o;List<String> keys=new ArrayList<>();Iterator<String> iter=d.keys();while(iter.hasNext())keys.add(iter.next());Collections.sort(keys);List<String> parts=new ArrayList<>();for(String k:keys)parts.add(JSONObject.quote(k)+":"+canonical(d.get(k)));return "{"+String.join(",",parts)+"}";}if(o instanceof JSONArray){List<String> parts=new ArrayList<>();JSONArray a=(JSONArray)o;for(int i=0;i<a.length();i++)parts.add(canonical(a.get(i)));return "["+String.join(",",parts)+"]";}if(o instanceof String)return JSONObject.quote((String)o);return o==null||o==JSONObject.NULL?"null":String.valueOf(o);}
 public static JSONObject export(Vault v)throws Exception{validate(v);JSONObject o=new JSONObject();o.put("format","Vaultline.Export");o.put("version",1);o.put("exportedAt",now());o.put("folders",new JSONArray(v.folders));JSONArray a=new JSONArray();for(Entry e:v.entries){JSONObject r=new JSONObject();r.put("path",e.path);r.put("label",name(e.path));r.put("level",e.level);r.put("updated",e.updated==null?JSONObject.NULL:e.updated);r.put("fields",e.fields);a.put(r);}o.put("entries",a);return o;}
 public static Vault parseExport(String text)throws Exception{JSONObject o=new JSONObject(text);if(!Arrays.asList("Vaultline.Export","Vaultline.GroupExport").contains(o.optString("format"))||!(o.opt("version") instanceof Number)||((Number)o.get("version")).doubleValue()!=1)throw new Exception("请选择 Vaultline 导出的 JSON 文件");Vault v=new Vault();JSONArray fs=o.getJSONArray("folders"),es=o.getJSONArray("entries");Set<String> seen=new HashSet<>();for(int i=0;i<fs.length();i++){Object f=fs.get(i);if(!(f instanceof String))throw new Exception("无效分组");String p=(String)f;path(p);if(!seen.add(p.toLowerCase(Locale.ROOT)))throw new Exception("重复分组");addFolder(v,p);}for(int i=0;i<es.length();i++){JSONObject e=es.getJSONObject(i);Object p=e.get("path"),l=e.get("level"),u=e.opt("updated");if(!(p instanceof String)||!(l instanceof String)||(u!=null&&u!=JSONObject.NULL&&!(u instanceof String)))throw new Exception("无效账号");put(v,new Entry((String)p,(String)l,e.getJSONObject("fields"),u==null||u==JSONObject.NULL?null:(String)u),null);}validate(v);return v;}
 static String available(Vault v,String p)throws Exception{String target=p;int n=2;while(entry(v,target)!=null||folder(v,target)!=null)target=p+"-import-"+n++;path(target);return target;}
 static boolean same(Entry a,Entry b)throws Exception{return a.level.equals(b.level)&&canonical(a.fields).equals(canonical(b.fields));}
 public static Merge merge(Vault current,Vault incoming)throws Exception{validate(current);validate(incoming);Merge r=new Merge();r.vault=current.copy();Vault v=r.vault;Map<String,String> map=new TreeMap<>(String.CASE_INSENSITIVE_ORDER);map.put("","");List<String> fs=new ArrayList<>(incoming.folders);Collections.sort(fs,(a,b)->{int c=Integer.compare(a.split("/").length,b.split("/").length);return c==0?a.compareToIgnoreCase(b):c;});for(String f:fs){String p=map.get(parent(f));String dest=(p.isEmpty()?"":p+"/")+name(f);if(entry(v,dest)!=null)dest=available(v,dest);addFolder(v,dest);map.put(f,dest);}for(Entry e:incoming.entries){String p=map.get(parent(e.path));String dest=(p.isEmpty()?"":p+"/")+name(e.path);Entry old=entry(v,dest);if(old!=null&&same(old,e)){r.skipped++;continue;}boolean duplicate=false;if(old!=null)for(Entry x:v.entries)if(eq(parent(x.path),p)&&x.path.toLowerCase(Locale.ROOT).startsWith((dest+"-import-").toLowerCase(Locale.ROOT))&&same(x,e)){duplicate=true;break;}if(duplicate){r.skipped++;continue;}String target=available(v,dest);if(!eq(target,e.path))r.renamed++;Entry n=e.copy();n.path=target;put(v,n,null);r.added++;}validate(v);return r;}
 public static void moveFolder(Vault v,String from,String to)throws Exception{path(to);if(eq(from,to))return;if(under(to,from)||folder(v,to)!=null||entry(v,to)!=null)throw new Exception("目标路径冲突或位于自身子目录");List<String> affected=new ArrayList<>();for(String f:v.folders)if(under(f,from))affected.add(f);v.folders.removeAll(affected);for(String f:affected)addFolder(v,to+f.substring(from.length()));for(Entry e:v.entries)if(under(e.path,from))e.path=to+e.path.substring(from.length());validate(v);}
 public static byte[] serialize(Vault v)throws Exception{validate(v);JSONObject o=new JSONObject();o.put("Version",1);o.put("Folders",new JSONArray(v.folders));JSONArray a=new JSONArray();for(Entry e:v.entries){JSONObject j=new JSONObject();j.put("Path",e.path);j.put("Level",e.level);j.put("Fields",e.fields);j.put("Updated",e.updated==null?JSONObject.NULL:e.updated);a.put(j);}o.put("Entries",a);return o.toString().getBytes(StandardCharsets.UTF_8);}
 public static Vault deserialize(byte[] b)throws Exception{JSONObject o=new JSONObject(new String(b,StandardCharsets.UTF_8));if(o.getInt("Version")!=1)throw new Exception("不支持的保险库版本");Vault v=new Vault();JSONArray fs=o.getJSONArray("Folders"),es=o.getJSONArray("Entries");for(int i=0;i<fs.length();i++)v.folders.add(fs.getString(i));for(int i=0;i<es.length();i++){JSONObject e=es.getJSONObject(i);v.entries.add(new Entry(e.getString("Path"),e.getString("Level"),e.getJSONObject("Fields"),e.isNull("Updated")?null:e.getString("Updated")));}validate(v);return v;}
 public static final byte[] MAGIC="JINXIA01".getBytes(StandardCharsets.US_ASCII);
 public static byte[] random(int n){byte[] b=new byte[n];new SecureRandom().nextBytes(b);return b;}
 public static byte[] derive(char[] password,byte[] salt)throws Exception{PBEKeySpec spec=new PBEKeySpec(password,salt,600000,512);try{return SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256").generateSecret(spec).getEncoded();}finally{spec.clearPassword();}}
 public static byte[] salt(byte[] b)throws Exception{if(b.length<88||!Arrays.equals(Arrays.copyOf(b,8),MAGIC))throw new Exception("无效的 Vaultline 加密文件");return Arrays.copyOfRange(b,8,24);}
 public static byte[] seal(byte[] plain,byte[] key,byte[] salt)throws Exception{byte[] iv=random(16);Cipher c=Cipher.getInstance("AES/CBC/PKCS5Padding");c.init(Cipher.ENCRYPT_MODE,new SecretKeySpec(Arrays.copyOfRange(key,0,32),"AES"),new IvParameterSpec(iv));ByteArrayOutputStream out=new ByteArrayOutputStream();out.write(MAGIC);out.write(salt);out.write(iv);out.write(c.doFinal(plain));byte[] head=out.toByteArray();Mac mac=Mac.getInstance("HmacSHA256");mac.init(new SecretKeySpec(Arrays.copyOfRange(key,32,64),"HmacSHA256"));out.write(mac.doFinal(head));return out.toByteArray();}
 public static byte[] open(byte[] b,byte[] key)throws Exception{salt(b);int n=b.length-32;Mac mac=Mac.getInstance("HmacSHA256");mac.init(new SecretKeySpec(Arrays.copyOfRange(key,32,64),"HmacSHA256"));if(!MessageDigest.isEqual(mac.doFinal(Arrays.copyOf(b,n)),Arrays.copyOfRange(b,n,b.length)))throw new Exception("主密码不正确，或文件已损坏");Cipher c=Cipher.getInstance("AES/CBC/PKCS5Padding");c.init(Cipher.DECRYPT_MODE,new SecretKeySpec(Arrays.copyOfRange(key,0,32),"AES"),new IvParameterSpec(Arrays.copyOfRange(b,24,40)));return c.doFinal(Arrays.copyOfRange(b,40,n));}
 public static byte[] read(InputStream in)throws Exception{try(InputStream input=in;ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] buffer=new byte[8192];int n;while((n=input.read(buffer))!=-1){if(out.size()+n>LIMIT)throw new Exception("文件过大，最多支持 32 MB");out.write(buffer,0,n);}return out.toByteArray();}}
 public static void atomic(File file,byte[] bytes)throws Exception{File temp=new File(file.getPath()+".tmp");try{try(FileOutputStream out=new FileOutputStream(temp)){out.write(bytes);out.getFD().sync();}if(file.exists())Files.copy(file.toPath(),new File(file.getPath()+".bak").toPath(),StandardCopyOption.REPLACE_EXISTING);try{Files.move(temp.toPath(),file.toPath(),StandardCopyOption.REPLACE_EXISTING,StandardCopyOption.ATOMIC_MOVE);}catch(AtomicMoveNotSupportedException ex){Files.move(temp.toPath(),file.toPath(),StandardCopyOption.REPLACE_EXISTING);}}finally{if(temp.exists())temp.delete();}}
}
