using System;
using System.IO;
using System.Linq;
using System.Drawing;
using System.Windows.Forms;
using System.Collections.Generic;
using System.Diagnostics;
using Microsoft.Win32;
using System.Runtime.InteropServices;

namespace Vaultline {
 public static class Theme {
  [DllImport("dwmapi.dll")] static extern int DwmSetWindowAttribute(IntPtr hwnd,int attribute,ref int value,int size);
  [DllImport("uxtheme.dll",CharSet=CharSet.Unicode)] static extern int SetWindowTheme(IntPtr hwnd,string app,string id);
  [DllImport("user32.dll",CharSet=CharSet.Unicode)] static extern IntPtr SendMessage(IntPtr hwnd,int msg,IntPtr w,string text);
  public static void Dark(Form f){f.HandleCreated+=(s,e)=>{try{int dark=1;DwmSetWindowAttribute(f.Handle,20,ref dark,4);}catch{}};}
  public static void Hint(TextBox t,string text){SendMessage(t.Handle,0x1501,(IntPtr)1,text);}
  public static void Explorer(TreeView tree,ListView list){
   tree.DrawMode=TreeViewDrawMode.OwnerDrawAll;
   tree.DrawNode+=(s,e)=>{
    e.DrawDefault=false;if(e.Bounds.Height<=0)return;
    bool selected=e.Node.IsSelected;Color ink=selected?Bg:Text;
    var row=new Rectangle(0,e.Bounds.Y,tree.ClientSize.Width,e.Bounds.Height);
    using(var brush=new SolidBrush(selected?Gold:Bg))e.Graphics.FillRectangle(brush,row);
    Rectangle label=e.Node.Bounds;label.Y=row.Y;label.Height=row.Height;label.Width=Math.Max(0,tree.ClientSize.Width-label.X-6);
    if(e.Node.Nodes.Count>0){int x=label.X-12,y=row.Y+row.Height/2;Point[] points=e.Node.IsExpanded?new[]{new Point(x-4,y-2),new Point(x+4,y-2),new Point(x,y+3)}:new[]{new Point(x-2,y-4),new Point(x-2,y+4),new Point(x+3,y)};using(var brush=new SolidBrush(ink))e.Graphics.FillPolygon(brush,points);}
    TextRenderer.DrawText(e.Graphics,e.Node.Text,tree.Font,label,ink,TextFormatFlags.Left|TextFormatFlags.VerticalCenter|TextFormatFlags.EndEllipsis|TextFormatFlags.NoPrefix);
   };
   tree.AfterSelect+=(s,e)=>tree.Invalidate();tree.GotFocus+=(s,e)=>tree.Invalidate();tree.LostFocus+=(s,e)=>tree.Invalidate();
   list.OwnerDraw=true;list.DrawColumnHeader+=(s,e)=>{using(var b=new SolidBrush(Panel))e.Graphics.FillRectangle(b,e.Bounds);TextRenderer.DrawText(e.Graphics,e.Header.Text,list.Font,e.Bounds,Muted,TextFormatFlags.Left|TextFormatFlags.VerticalCenter);};list.DrawItem+=(s,e)=>{};list.DrawSubItem+=(s,e)=>{using(var b=new SolidBrush(e.Item.Selected?Gold:Bg))e.Graphics.FillRectangle(b,e.Bounds);var r=e.Bounds;r.Inflate(-6,0);TextRenderer.DrawText(e.Graphics,e.SubItem.Text,list.Font,r,e.Item.Selected?Bg:Text,TextFormatFlags.Left|TextFormatFlags.VerticalCenter|TextFormatFlags.EndEllipsis|TextFormatFlags.NoPrefix);};SetWindowTheme(tree.Handle,"","");SetWindowTheme(list.Handle,"DarkMode_Explorer",null);
  }
  public static Color Bg=Color.FromArgb(23,23,25),Panel=Color.FromArgb(32,32,34),Gold=Color.FromArgb(219,181,92),Text=Color.FromArgb(226,226,226),Muted=Color.FromArgb(155,155,155);
  public static void Apply(Control c){c.BackColor=Bg;c.ForeColor=Text;c.Font=new Font("Microsoft YaHei UI",10);foreach(Control child in c.Controls)Apply(child);var b=c as Button;if(b!=null){b.FlatStyle=FlatStyle.Flat;b.FlatAppearance.BorderColor=Color.FromArgb(73,69,58);b.BackColor=Panel;b.ForeColor=Gold;b.Cursor=Cursors.Hand;}var t=c as TextBox;if(t!=null){t.BackColor=Panel;t.BorderStyle=BorderStyle.FixedSingle;}var f=c as Form;if(f!=null){f.Icon=Icon.ExtractAssociatedIcon(Application.ExecutablePath);f.StartPosition=FormStartPosition.CenterScreen;Dark(f);}}
  public static Button Button(string text,Action action,int width){var b=new Button{Text=text,Width=width,Height=36,Margin=new Padding(4)};b.Click+=(s,e)=>action();return b;}
  public static void Error(Exception e){MessageBox.Show(e.Message,"Vaultline",MessageBoxButtons.OK,MessageBoxIcon.None);}
  public static string Ask(string title,string label,string initial,bool password){using(var f=new Form{Text=title,ClientSize=new Size(490,190),FormBorderStyle=FormBorderStyle.FixedDialog,MaximizeBox=false,MinimizeBox=false}){var l=new Label{Text=label,Left=24,Top=22,Width=445,Height=44};var t=new TextBox{Text=initial,Left=24,Top= seventy(),Width=440,UseSystemPasswordChar=password};var ok=Button("确定",()=>f.DialogResult=DialogResult.OK,100);ok.Left=364;ok.Top=126;f.Controls.AddRange(new Control[]{l,t,ok});f.AcceptButton=ok;Theme.Apply(f);return f.ShowDialog()==DialogResult.OK?t.Text:null;}}
  static int seventy(){return 74;}
 }
 public class UnlockForm:Form {
  TextBox pass,confirm;Label status;Store store;bool create;
  public UnlockForm(Store s){store=s;create=!File.Exists(s.FilePath);Text="Vaultline · "+(create?"创建保险库":"解锁保险库");ClientSize=new Size(550,435);FormBorderStyle=FormBorderStyle.FixedDialog;MaximizeBox=false;MinimizeBox=false;
   Controls.Add(new Label{Text="VAULTLINE",Left=34,Top=30,Width=480,Height=40,Font=new Font("Microsoft YaHei UI",23,FontStyle.Bold)});
   Controls.Add(new Label{Text=create?"为本地保险库设置主密码（至少 12 个字符）":"你的隐私，只存放在你的电脑。",Left=34,Top=88,Width=480,Height=30});
   pass=new TextBox{Left=34,Top=136,Width=480,UseSystemPasswordChar=true};Controls.Add(pass);
   if(create){Controls.Add(new Label{Text="再次输入主密码",Left=34,Top=185,Width=470});confirm=new TextBox{Left=34,Top=216,Width=480,UseSystemPasswordChar=true};Controls.Add(confirm);}
   status=new Label{Text=create?"请妥善保管主密码；遗失后无法恢复数据。":"",Left=34,Top=267,Width=480,Height=45};Controls.Add(status);
   var b=Theme.Button(create?"创建并进入":"解锁",Unlock,480);b.Left=30;b.Top=320;Controls.Add(b);AcceptButton=b;
   Controls.Add(new Label{Text="存储位置："+Path.GetDirectoryName(s.FilePath),Left=34,Top=378,Width=480,Height=42,AutoEllipsis=true});Theme.Apply(this);Controls[0].Font=new Font("Microsoft YaHei UI",23,FontStyle.Bold);Controls[0].ForeColor=Theme.Gold;
  }
  void Unlock(){try{if(create&&(pass.Text.Length<12||pass.Text!=confirm.Text))throw new Exception("主密码至少 12 个字符，且两次输入必须一致。");UseWaitCursor=true;store.Unlock(pass.Text);if(create)store.Save();pass.Clear();if(confirm!=null)confirm.Clear();DialogResult=DialogResult.OK;}catch(Exception e){status.Text=e.Message;}finally{UseWaitCursor=false;}}
 }
 public class Editor:Form {
  public Entry Result;TextBox path,json;ComboBox level;
  public Editor(string folder,Entry entry){Text=entry==null?"新建账号 JSON":"编辑账号 JSON";ClientSize=new Size(760,650);MinimumSize=new Size(650,560);
   var layout=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(24),ColumnCount=1,RowCount=8};layout.RowStyles.Add(new RowStyle(SizeType.Absolute,30));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,44));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,30));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,44));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,35));layout.RowStyles.Add(new RowStyle(SizeType.Percent,100));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,38));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,46));
   path=new TextBox{Dock=DockStyle.Top,Text=entry==null?(folder==""?"":folder+"/")+"work-account":entry.Path};level=new ComboBox{Dock=DockStyle.Top,DropDownStyle=ComboBoxStyle.DropDownList};level.Items.AddRange(new object[]{"普通","敏感","机密"});level.SelectedItem=entry==null?"敏感":entry.Level;if(level.SelectedIndex<0)level.SelectedIndex=1;
   json=new TextBox{Dock=DockStyle.Fill,Multiline=true,AcceptsReturn=true,AcceptsTab=true,ScrollBars=ScrollBars.Both,WordWrap=false,Text=entry==null?"{\r\n  \"微信号\": \"\",\r\n  \"password\": \"\",\r\n  \"绑定的手机号\": \"\",\r\n  \"绑定的银行卡\": \"\"\r\n}":Engine.Pretty(entry.Fields)};
   layout.Controls.Add(new Label{Text="完整路径 / 最后一段即唯一标签",AutoSize=true});layout.Controls.Add(path);layout.Controls.Add(new Label{Text="隐私级别（所有级别均加密）",AutoSize=true});layout.Controls.Add(level);layout.Controls.Add(new Label{Text="账号内容 · JSON 对象（编辑时可见明文）",AutoSize=true});layout.Controls.Add(json);layout.Controls.Add(new Label{Text="路径示例 account/wechat/work-account · 字段可使用中文或英文",AutoSize=true});
   var buttons=new FlowLayoutPanel{Dock=DockStyle.Fill,FlowDirection=FlowDirection.RightToLeft};buttons.Controls.Add(Theme.Button("保存",Save,100));buttons.Controls.Add(Theme.Button("取消",()=>Close(),90));buttons.Controls.Add(Theme.Button("格式化",()=>{try{json.Text=Engine.Pretty(Parse());}catch(Exception e){Theme.Error(e);}},95));layout.Controls.Add(buttons);Controls.Add(layout);Theme.Apply(this);json.Font=new Font("Consolas",11);
  }
  Dictionary<string,object> Parse(){var d=Engine.Json.DeserializeObject(json.Text) as Dictionary<string,object>;if(d==null)throw new Exception("请输入有效的 JSON 对象，例如 {\"password\":\"...\"}。");return d;}
  void Save(){try{string p=Engine.Normalize(path.Text);Engine.ValidatePath(p);Result=new Entry{Path=p,Fields=Parse(),Level=level.Text,Updated=DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss")};DialogResult=DialogResult.OK;}catch(Exception e){Theme.Error(e);}}
 }
 public class Activity:IMessageFilter {public DateTime Last=DateTime.UtcNow;public bool PreFilterMessage(ref Message m){if(m.Msg==0x100||m.Msg==0x201||m.Msg==0x204||m.Msg==0x20A||m.Msg==0x200)Last=DateTime.UtcNow;return false;}}
 public class MainForm:Form {
  Store store;TreeView tree;ListView list;TextBox search,detail;Label heading,meta,status;Button reveal;Entry selected;object selectedValue;bool shown,locking,loading;string folder="",selectedFolder;DateTime showUntil;Timer timer=new Timer{Interval=1000};Activity activity=new Activity();
  public MainForm(Store s){store=s;Text="Vaultline · 离线隐私管理";ClientSize=new Size(1280,800);MinimumSize=new Size(1050,680);
   var root=new TableLayoutPanel{Dock=DockStyle.Fill,RowCount=5,ColumnCount=1,Padding=new Padding(22)};root.RowStyles.Add(new RowStyle(SizeType.Absolute,70));root.RowStyles.Add(new RowStyle(SizeType.Absolute,55));root.RowStyles.Add(new RowStyle(SizeType.AutoSize));root.RowStyles.Add(new RowStyle(SizeType.Percent,100));root.RowStyles.Add(new RowStyle(SizeType.Absolute,36));
   var top=new Panel{Dock=DockStyle.Fill};var title=new Label{Text="Vaultline",Left=0,Top=0,Width=205,Height=45};var subtitle=new Label{Text="本地隐私保险库",Left=220,Top=17,Width=420,Height=30};var secure=new Label{Text="●  离线存储   /   已加密",Dock=DockStyle.Right,Width=215,TextAlign=ContentAlignment.MiddleRight};top.Controls.AddRange(new Control[]{title,subtitle,secure});root.Controls.Add(top);
   var searchPanel=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2};searchPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));searchPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,106));search=new TextBox{Dock=DockStyle.Fill,Margin=new Padding(0,7,10,0)};search.KeyDown+=(o,e)=>{if(e.KeyCode==Keys.Enter){Search();e.SuppressKeyPress=true;}};searchPanel.Controls.Add(search);searchPanel.Controls.Add(Theme.Button("搜索 / 跳转",Search,100));root.Controls.Add(searchPanel);
   var bar=new FlowLayoutPanel{Dock=DockStyle.Fill,WrapContents=true,AutoSize=true,AutoSizeMode=AutoSizeMode.GrowAndShrink};bar.Controls.Add(Theme.Button("＋ 分组",NewFolder,95));bar.Controls.Add(Theme.Button("＋ 账号",()=>Edit(true),95));bar.Controls.Add(Theme.Button("编辑 / 移动",()=>Edit(false),110));bar.Controls.Add(Theme.Button("删除",Delete,72));bar.Controls.Add(Theme.Button("加密备份",Backup,95));bar.Controls.Add(Theme.Button("恢复备份",Restore,95));bar.Controls.Add(Theme.Button("主密码",Password,80));bar.Controls.Add(Theme.Button("锁定",Lock,72));bar.Controls.Add(Theme.Button("导出数据",ExportAll,90));bar.Controls.Add(Theme.Button("一键导入",ImportAll,90));bar.Controls.Add(Theme.Button("帮助",Help,70));root.Controls.Add(bar);
   var panes=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=3,RowCount=1};panes.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,240));panes.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,48));panes.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,52));
   tree=new TreeView{Dock=DockStyle.Fill,BorderStyle=BorderStyle.None,HideSelection=false,FullRowSelect=true,ItemHeight=32,ShowLines=false};tree.AfterSelect+=(o,e)=>{if(loading)return;folder=(string)e.Node.Tag;search.Clear();RefreshList(null);};panes.Controls.Add(tree);
   list=new ListView{Dock=DockStyle.Fill,View=View.Details,FullRowSelect=true,HideSelection=false,MultiSelect=false,BorderStyle=BorderStyle.None};list.Columns.Add("标签 / 名称",190);list.Columns.Add("隐私级别",80);list.Columns.Add("所在目录",260);list.SelectedIndexChanged+=(o,e)=>{if(list.SelectedItems.Count>0){var item=list.SelectedItems[0];if(item.Tag is Entry)Select((Entry)item.Tag,null,false);else {ClearDetail();selectedFolder=(string)item.Tag;}}};list.DoubleClick+=(o,e)=>{if(list.SelectedItems.Count>0&&list.SelectedItems[0].Tag is string)Navigate((string)list.SelectedItems[0].Tag);};panes.Controls.Add(list);
   var right=new TableLayoutPanel{Dock=DockStyle.Fill,RowCount=5,ColumnCount=1,Padding=new Padding(18,6,0,0)};right.RowStyles.Add(new RowStyle(SizeType.Absolute,45));right.RowStyles.Add(new RowStyle(SizeType.Absolute,72));right.RowStyles.Add(new RowStyle(SizeType.Percent,100));right.RowStyles.Add(new RowStyle(SizeType.Absolute,48));right.RowStyles.Add(new RowStyle(SizeType.Absolute,45));heading=new Label{Text="账号详情",Dock=DockStyle.Fill};meta=new Label{Dock=DockStyle.Fill,AutoEllipsis=true};detail=new TextBox{Dock=DockStyle.Fill,Multiline=true,ReadOnly=true,ScrollBars=ScrollBars.Both,WordWrap=false};right.Controls.Add(heading);right.Controls.Add(meta);right.Controls.Add(detail);var actions=new FlowLayoutPanel{Dock=DockStyle.Fill};reveal=Theme.Button("显示 30 秒",Reveal,115);actions.Controls.Add(reveal);actions.Controls.Add(Theme.Button("复制内容",Copy,100));right.Controls.Add(actions);right.Controls.Add(new Label{Text="闲置 5 分钟自动锁定",Dock=DockStyle.Fill});panes.Controls.Add(right);root.Controls.Add(panes);status=new Label{Dock=DockStyle.Fill,TextAlign=ContentAlignment.BottomLeft};root.Controls.Add(status);Controls.Add(root);
   Theme.Apply(this);title.Font=new Font("Microsoft YaHei UI",25,FontStyle.Bold);title.ForeColor=secure.ForeColor=Theme.Gold;heading.Font=new Font("Microsoft YaHei UI",15,FontStyle.Bold);detail.Font=new Font("Consolas",11);tree.LineColor=Theme.Muted;Theme.Explorer(tree,list);Theme.Hint(search,"输入目录 / 标签 / 字段，例如 account/wechat/work-account/password");Application.AddMessageFilter(activity);timer.Tick+=Tick;timer.Start();SystemEvents.SessionSwitch+=SessionSwitch;FormClosed+=(o,e)=>{timer.Stop();timer.Dispose();SystemEvents.SessionSwitch-=SessionSwitch;Application.RemoveMessageFilter(activity);store.Dispose();};KeyPreview=true;KeyDown+=(o,e)=>{if(e.Control&&e.KeyCode==Keys.L){Lock();e.SuppressKeyPress=true;}if(e.Control&&e.KeyCode==Keys.F){search.Focus();search.SelectAll();e.SuppressKeyPress=true;}};Rebuild();
  }
  void SessionSwitch(object s,SessionSwitchEventArgs e){if(e.Reason==SessionSwitchReason.SessionLock&&IsHandleCreated)BeginInvoke(new Action(Lock));}
  void Tick(object s,EventArgs e){if(shown&&DateTime.UtcNow>=showUntil){shown=false;Render();}if(!locking&&DateTime.UtcNow-activity.Last>TimeSpan.FromMinutes(5))Lock();}
  void ClearDetail(){selectedFolder=null;selected=null;selectedValue=null;shown=false;heading.Text="账号详情";meta.Text="选择一个账号，或输入完整路径定位字段。";detail.Text="\r\n  隐私信息默认隐藏\r\n\r\n  路径示例：\r\n  account/wechat/work-account/password";reveal.Text="显示 30 秒";}
  void Select(Entry e,object value,bool isField){selected=e;selectedValue=isField?value:e.Fields;shown=false;heading.Text=Engine.Name(e.Path);meta.Text=e.Path+"\r\n"+e.Level+"  ·  "+e.Updated;Render();}
  void Render(){reveal.Text=shown?"隐藏内容":"显示 30 秒";if(selected==null)return;if(shown)detail.Text=Engine.DisplayLines(selectedValue);else{var d=selectedValue as Dictionary<string,object>;detail.Text=d==null?"••••••••":string.Join("\r\n\r\n",d.Keys.Select(k=>k+"  :  ••••••••"));}}
  void Reveal(){if(selected==null)return;shown=!shown;showUntil=DateTime.UtcNow.AddSeconds(30);Render();}
  void Copy(){if(selected==null)return;try{string text=Engine.CopyLines(selectedValue);if(text.Length==0){status.Text="当前内容为空，没有可复制的值。";return;}Clipboard.SetText(text);status.Text="已复制内容";}catch(Exception e){Theme.Error(e);}}
  void ExportAll(){
   if(locking||store.Value==null)return;
   using(var dialog=new SaveFileDialog{Title="导出全部数据",Filter="JSON 数据文件|*.json",DefaultExt="json",AddExtension=true,OverwritePrompt=true,FileName="Vaultline-"+DateTime.Now.ToString("yyyyMMdd-HHmmss")+".json"}){
    if(dialog.ShowDialog(this)!=DialogResult.OK||locking||store.Value==null)return;
    try{Engine.WriteExport(dialog.FileName,Engine.ExportAll(store.Value),store.FilePath);status.Text="已导出 "+store.Value.Entries.Count+" 个账号："+dialog.FileName;}catch(Exception e){Theme.Error(e);}
   }
  }
  void ImportAll(){
   if(locking||store.Value==null)return;
   using(var dialog=new OpenFileDialog{Title="一键导入",Filter="Vaultline 导出文件|*.json",Multiselect=false}){
    if(dialog.ShowDialog(this)!=DialogResult.OK||locking||store.Value==null)return;
    Vault previous=store.Value;
    try{
     if(new FileInfo(dialog.FileName).Length>32000000)throw new Exception("导入文件过大，最多支持 32 MB。");
     var incoming=Engine.ParseImport(File.ReadAllText(dialog.FileName));var result=Engine.MergeImport(previous,incoming);
     store.Value=result.Value;store.Save();Rebuild();status.Text="已导入 "+result.Added+" 个账号，跳过 "+result.Skipped+" 个重复账号，重命名 "+result.Renamed+" 个冲突账号";
    }catch(Exception e){store.Value=previous;Rebuild();Theme.Error(e);}
   }
  }
  void Rebuild(){loading=true;tree.Nodes.Clear();var root=new TreeNode("保险库"){Tag=""};tree.Nodes.Add(root);var map=new Dictionary<string,TreeNode>(StringComparer.OrdinalIgnoreCase);map[""]=root;foreach(string p in store.Value.Folders.OrderBy(x=>x.Count(c=>c=='/')).ThenBy(x=>x)){var n=new TreeNode(Engine.Name(p)){Tag=p};map[Engine.Parent(p)].Nodes.Add(n);map[p]=n;}root.Expand();if(!map.ContainsKey(folder))folder="";tree.SelectedNode=map[folder];tree.SelectedNode.EnsureVisible();loading=false;RefreshList(null);}
  void Navigate(string p){folder=p;Rebuild();}
  void RefreshList(IEnumerable<Entry> results){list.Items.Clear();ClearDetail();if(results==null){foreach(string f in store.Value.Folders.Where(f=>Engine.Equal(Engine.Parent(f),folder)).OrderBy(x=>x)){var item=new ListViewItem("▸  "+Engine.Name(f)){Tag=f};item.SubItems.Add("分组");item.SubItems.Add(f);list.Items.Add(item);}results=store.Value.Entries.Where(x=>Engine.Equal(Engine.Parent(x.Path),folder));}foreach(var e in results.OrderBy(x=>x.Path)){var item=new ListViewItem(Engine.Name(e.Path)){Tag=e};item.SubItems.Add(e.Level);item.SubItems.Add(Engine.Parent(e.Path));list.Items.Add(item);}status.Text="位置："+(folder==""?"保险库":folder)+"   ·   "+store.Value.Entries.Count+" 个账号   ·   "+Path.GetDirectoryName(store.FilePath);}
  void Search(){try{string q=Engine.Normalize(search.Text);if(q==""){RefreshList(null);return;}string f=store.Value.Folders.FirstOrDefault(x=>Engine.Equal(x,q));if(f!=null){Navigate(f);return;}Entry e;object value=Engine.Resolve(store.Value,q,out e);if(e!=null){RefreshList(new[]{e});Select(e,value,!Engine.Equal(e.Path,q));status.Text="已定位："+q+"   ·   点击显示或复制内容";return;}RefreshList(store.Value.Entries.Where(x=>x.Path.IndexOf(q,StringComparison.OrdinalIgnoreCase)>=0));status.Text="找到 "+list.Items.Count+" 个账号（仅搜索目录和标签，不扫描秘密字段）。";}catch(Exception e){ClearDetail();Theme.Error(e);}}
  void Mutate(Action action){string before=Engine.Json.Serialize(store.Value);try{action();store.Save();Rebuild();}catch(Exception e){store.Value=Engine.Json.Deserialize<Vault>(before);Rebuild();Theme.Error(e);}}
  void NewFolder(){string name=Theme.Ask("新建分组","输入完整目录路径，例如 account/wechat",folder==""?"":folder+"/",false);if(name!=null)Mutate(()=>Engine.AddFolder(store.Value,Engine.Normalize(name)));}
  void Edit(bool create){string activeFolder=selectedFolder??folder;if(!create&&selected==null){if(activeFolder=="")return;string name=Theme.Ask("重命名 / 移动分组","输入新的完整路径",activeFolder,false);if(name==null)return;string target=Engine.Normalize(name),source=activeFolder;Mutate(()=>{Engine.ValidatePath(target);if(Engine.Equal(source,target))return;if(Engine.Under(target,source))throw new Exception("不能把目录移动到自己的子目录。");var affected=store.Value.Folders.Where(x=>Engine.Under(x,source)).ToList();var records=store.Value.Entries.Where(x=>Engine.Under(x.Path,source)).ToList();if(store.Value.Folders.Any(x=>!affected.Contains(x)&&Engine.Equal(x,target))||store.Value.Entries.Any(x=>Engine.Equal(x.Path,target)))throw new Exception("目标路径已存在。");store.Value.Folders.RemoveAll(x=>affected.Contains(x));foreach(string x in affected)Engine.AddFolder(store.Value,target+x.Substring(source.Length));foreach(Entry x in records)x.Path=target+x.Path.Substring(source.Length);folder=target;});return;}Entry old=create?null:selected;using(var f=new Editor(activeFolder,old)){if(f.ShowDialog(this)==DialogResult.OK)Mutate(()=>Engine.Put(store.Value,f.Result,old));}}
  void Delete(){if(selected!=null){Entry e=selected;if(MessageBox.Show("删除账号 “"+Engine.Name(e.Path)+"”？","Vaultline",MessageBoxButtons.YesNo,MessageBoxIcon.None)==DialogResult.Yes)Mutate(()=>store.Value.Entries.Remove(e));}else if((selectedFolder??folder)!=""){string f=selectedFolder??folder;int count=store.Value.Entries.Count(x=>Engine.Under(x.Path,f));if(MessageBox.Show("删除分组 “"+f+"” 及其全部子目录和 "+count+" 个账号？","Vaultline",MessageBoxButtons.YesNo,MessageBoxIcon.None)==DialogResult.Yes)Mutate(()=>{store.Value.Entries.RemoveAll(x=>Engine.Under(x.Path,f));store.Value.Folders.RemoveAll(x=>Engine.Under(x,f));folder=Engine.Parent(f);});}}
  void Backup(){using(var d=new SaveFileDialog{Filter="Vaultline加密备份|*.jx",FileName="Vaultline备份-"+DateTime.Now.ToString("yyyyMMdd-HHmmss")+".jx"})if(d.ShowDialog()==DialogResult.OK){try{if(Path.GetFullPath(d.FileName).Equals(Path.GetFullPath(store.FilePath),StringComparison.OrdinalIgnoreCase))throw new Exception("请选择保险库以外的备份文件。");File.Copy(store.FilePath,d.FileName,true);status.Text="加密备份已保存："+d.FileName;}catch(Exception e){Theme.Error(e);}}}
  void Restore(){using(var d=new OpenFileDialog{Filter="Vaultline加密文件|*.jx;*.bak"})if(d.ShowDialog()==DialogResult.OK){string p=Theme.Ask("恢复备份","输入该备份创建时的主密码","",true);if(p==null)return;byte[] k=null,plain=null;try{byte[] b=File.ReadAllBytes(d.FileName);k=Crypto.Derive(p,Crypto.Salt(b));plain=Crypto.Open(b,k);Vault v=Engine.Json.Deserialize<Vault>(System.Text.Encoding.UTF8.GetString(plain));Engine.Validate(v);if(MessageBox.Show("备份含 "+v.Entries.Count+" 个账号，将替换当前保险库。继续？\r\n替换前会保存一份自动备份。","恢复备份",MessageBoxButtons.YesNo,MessageBoxIcon.None)==DialogResult.Yes){File.Copy(store.FilePath,store.FilePath+".before-restore-"+DateTime.Now.ToString("yyyyMMddHHmmss"),false);Mutate(()=>store.Value=v);}}catch(Exception e){Theme.Error(e);}finally{if(k!=null)Array.Clear(k,0,k.Length);if(plain!=null)Array.Clear(plain,0,plain.Length);}}}
  void Password(){string p=Theme.Ask("更改主密码","输入新主密码（至少 12 个字符）","",true);if(p==null)return;if(p.Length<12){Theme.Error(new Exception("主密码至少 12 个字符。"));return;}string c=Theme.Ask("确认主密码","再次输入新主密码","",true);if(c==null)return;if(p!=c){Theme.Error(new Exception("两次输入不一致。"));return;}try{store.ChangePassword(p);MessageBox.Show("主密码已更新。历史备份仍需使用备份时的密码。","Vaultline");}catch(Exception e){Theme.Error(e);}}
  void Lock(){if(locking)return;locking=true;foreach(Form f in Application.OpenForms.Cast<Form>().Where(f=>f!=this).ToArray()){f.DialogResult=DialogResult.Cancel;f.Close();}ClearDetail();list.Items.Clear();tree.Nodes.Clear();search.Clear();store.Lock();Hide();using(var f=new UnlockForm(store)){if(f.ShowDialog()==DialogResult.OK){activity.Last=DateTime.UtcNow;Rebuild();Show();Activate();locking=false;}else Close();}}
  void Help(){MessageBox.Show("目录：新建分组，支持多级路径；双击分组进入。\r\n账号：一个标签对应一个 JSON 对象；编辑完整路径即可移动。\r\n搜索：account/wechat/work-account\r\n字段：account/wechat/work-account/password\r\n嵌套字段：.../bank/card；数组：.../cards/0\r\n字段名中的 / 写为 ~1，~ 写为 ~0；字段名区分大小写。\r\n隐私分级：普通 / 敏感 / 机密，全部加密且默认隐藏。\r\nCtrl+F 搜索；Ctrl+L 锁定。闲置 5 分钟或系统锁屏自动锁定。\r\n编辑窗闲置锁定会丢弃尚未保存的内容。\r\n复制内容按行输出字段值；定位单个字段时可直接复制登录。\r\n导出数据会保存全部分组和账号；一键导入支持其他设备的导出文件，冲突项保留双方。\r\n请定期备份。主密码遗失无法恢复；系统剪贴板历史可能保留复制内容。\r\n\r\n存储："+store.FilePath,"Vaultline · 使用说明");}
 }
 public static class Program {
  [STAThread] public static void Main(string[] args){Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);if(args.Contains("--self-test")){SelfTest.Run();return;}if(args.Contains("--preview")){try{Preview.Run();}catch(Exception error){File.WriteAllText(Path.GetFullPath(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"..","tests","ui-results.txt")),error.ToString());Environment.ExitCode=1;}return;}try{string dir=StoragePaths.ResolveData(AppDomain.CurrentDomain.BaseDirectory);var store=new Store(dir);using(var unlock=new UnlockForm(store)){if(unlock.ShowDialog()!=DialogResult.OK){store.Dispose();return;}}Application.Run(new MainForm(store));}catch(Exception e){Theme.Error(new Exception("无法打开Vaultline："+e.Message+"\r\n若已打开另一个Vaultline窗口，请先关闭它。"));}}
 }
}
