using System;
using System.IO;
using System.Drawing;
using System.Windows.Forms;
using System.Reflection;
using Microsoft.Win32;

class Setup:Form {
 TextBox install,data;CheckBox desktop;Label state;Button go;
 public Setup(){Text="Vaultline · 安装向导";ClientSize=new Size(640,440);FormBorderStyle=FormBorderStyle.FixedDialog;MaximizeBox=false;StartPosition=FormStartPosition.CenterScreen;BackColor=Color.FromArgb(23,23,25);ForeColor=Color.Gainsboro;Font=new Font("Microsoft YaHei UI",10);Icon=Icon.ExtractAssociatedIcon(Application.ExecutablePath);
  Controls.Add(new Label{Text="VAULTLINE",Left=30,Top=25,Width=570,Height=48,Font=new Font("Microsoft YaHei UI",24,FontStyle.Bold),ForeColor=Color.FromArgb(219,181,92)});
  Controls.Add(new Label{Text="离线隐私管理  ·  目录与路径搜索  ·  本地加密",Left=32,Top=85,Width=575,Height=30});
  Controls.Add(new Label{Text="安装位置",Left=32,Top=133,Width=180});install=Box(Vaultline.StoragePaths.DefaultInstall,164);
  Controls.Add(new Label{Text="数据位置（卸载时保留）",Left=32,Top=214,Width=400});data=Box(Vaultline.StoragePaths.DefaultData,245);
  desktop=new CheckBox{Text="创建桌面快捷方式",Checked=true,Left=32,Top=294,Width=300};Controls.Add(desktop);state=new Label{Left=32,Top=337,Width=570,Height=30,Text="无需联网，无需管理员权限。"};Controls.Add(state);go=new Button{Text="安装Vaultline",Left=420,Top=375,Width=185,Height=40,FlatStyle=FlatStyle.Flat,ForeColor=Color.FromArgb(219,181,92)};go.Click+=(s,e)=>Install();Controls.Add(go);
  install.TextChanged+=(s,e)=>LoadExistingData();
  try{using(var key=Registry.CurrentUser.OpenSubKey(@"Software\Microsoft\Windows\CurrentVersion\Uninstall\Vaultline")){string existing=key==null?null:key.GetValue("InstallLocation") as string;if(!string.IsNullOrWhiteSpace(existing)&&Directory.Exists(existing))install.Text=existing;}}catch{}
  LoadExistingData();
 }
 void LoadExistingData(){try{string config=Path.Combine(install.Text.Trim(),"data-path.txt");if(File.Exists(config)){string existing=File.ReadAllText(config).Trim();if(Path.IsPathRooted(existing)){data.Text=existing;state.Text="已识别原数据位置；升级保留保险库和主密码。";}}}catch{}}
 TextBox Box(string text,int y){var t=new TextBox{Text=text,Left=32,Top=y,Width=470,BackColor=Color.FromArgb(35,35,37),ForeColor=Color.Gainsboro};Controls.Add(t);var b=new Button{Text="浏览",Left=514,Top=y-2,Width=90,Height=31,FlatStyle=FlatStyle.Flat};b.Click+=(s,e)=>{using(var d=new FolderBrowserDialog{SelectedPath=t.Text})if(d.ShowDialog()==DialogResult.OK)t.Text=d.SelectedPath;};Controls.Add(b);return t;}
 public static void Extract(string resource,string target){using(var s=Assembly.GetExecutingAssembly().GetManifestResourceStream(resource)){if(s==null)throw new Exception("安装包资源缺失。");using(var f=File.Create(target))s.CopyTo(f);}}
 void Shortcut(string path,string target,string icon){Type t=Type.GetTypeFromProgID("WScript.Shell");dynamic shell=Activator.CreateInstance(t);dynamic l=shell.CreateShortcut(path);l.TargetPath=target;l.WorkingDirectory=Path.GetDirectoryName(target);l.IconLocation=icon;l.Description="Vaultline · 离线隐私管理";l.Save();System.Runtime.InteropServices.Marshal.FinalReleaseComObject(l);System.Runtime.InteropServices.Marshal.FinalReleaseComObject(shell);}
 void Install(){try{string target=Path.GetFullPath(install.Text.Trim()),storage=Path.GetFullPath(data.Text.Trim());if(!Path.IsPathRooted(install.Text)||!Path.IsPathRooted(data.Text))throw new Exception("请选择绝对路径。");Directory.CreateDirectory(target);Directory.CreateDirectory(storage);string cfg=Path.Combine(target,"data-path.txt");if(File.Exists(cfg)&&!string.Equals(File.ReadAllText(cfg).Trim(),storage,StringComparison.OrdinalIgnoreCase))throw new Exception("此处已有安装。请使用原数据位置："+File.ReadAllText(cfg).Trim());go.Enabled=false;Extract("Vaultline.exe",Path.Combine(target,"Vaultline.exe"));Extract("Vaultline.ico",Path.Combine(target,"Vaultline.ico"));Extract("Uninstall.exe",Path.Combine(target,"Uninstall.exe"));Extract("Vaultline.exe.config",Path.Combine(target,"Vaultline.exe.config"));File.WriteAllText(cfg,storage);string menu=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Programs),"Vaultline");Directory.CreateDirectory(menu);Shortcut(Path.Combine(menu,"Vaultline.lnk"),Path.Combine(target,"Vaultline.exe"),Path.Combine(target,"Vaultline.ico"));if(desktop.Checked)Shortcut(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.DesktopDirectory),"Vaultline.lnk"),Path.Combine(target,"Vaultline.exe"),Path.Combine(target,"Vaultline.ico"));using(var key=Registry.CurrentUser.CreateSubKey(@"Software\Microsoft\Windows\CurrentVersion\Uninstall\Vaultline")){key.SetValue("DisplayName","Vaultline");key.SetValue("DisplayVersion","1.0.0");key.SetValue("Publisher","Vaultline");key.SetValue("InstallLocation",target);key.SetValue("DisplayIcon",Path.Combine(target,"Vaultline.ico"));key.SetValue("UninstallString","\""+Path.Combine(target,"Uninstall.exe")+"\"");key.SetValue("NoModify",1);key.SetValue("NoRepair",1);}state.Text="安装完成。数据位置："+storage;MessageBox.Show("安装完成。你可以从桌面或开始菜单打开Vaultline。","Vaultline");Close();}catch(Exception e){MessageBox.Show("安装未完成："+e.Message,"Vaultline");go.Enabled=true;}}
 [STAThread] static void Main(string[] args){Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);if(args.Length==2&&args[0]=="--extract-test"){Directory.CreateDirectory(args[1]);foreach(string name in new[]{"Vaultline.exe","Vaultline.ico","Uninstall.exe","Vaultline.exe.config"})Extract(name,Path.Combine(args[1],name));return;}Application.Run(new Setup());}
}
